### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by coldserenity** [cerebral/cerebral-debugger#60]
I'm on Fedora 28 Linux with stock Gnome. 
I have configured my application to listen for a debugger and in the debugger trying to create a connection to the running project.
Following is what I receive immediately after specifying port and project name
![image](https://user-images.githubusercontent.com/758763/42965952-351c68c2-8ba4-11e8-99a2-e846168e877c.png)

**Comment by coldserenity** [comment]
Restart does no good. Stack trace text for convenience
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at Object.t.setComputedState [as function] (file:///opt/Cerebral%20Debugger/resources/app.asar/electron/build/bundle.js:20:174081)
at e.value (file:///opt/Cerebral%20Debugger/resources/app.asar/electron/build/bundle.js:1:40321)
at file:///opt/Cerebral%20Debugger/resources/app.asar/electron/build/bundle.js:1:45244
at r.executeBranchWrapper (file:///opt/Cerebral%20Debugger/resources/app.asar/electron/build/bundle.js:1:43008)
at t (file:///opt/Cerebral%20Debugger/resources/app.asar/electron/build/bundle.js:1:44472)
at n (file:///opt/Cerebral%20Debugger/resources/app.asar/electron/build/bundle.js:1:44499)
at file:///opt/Cerebral%20Debugger/resources/app.asar/electron/build/bundle.js:1:44810
at e.value (file:///opt/Cerebral%20Debugger/resources/app.asar/electron/build/bundle.js:1:41784)
at file:///opt/Cerebral%20Debugger/resources/app.asar/electron/build/bundle.js:1:45244

```

**Comment by rafaelbusetti** [comment]
Also here. (version windows 3.0.0)

`TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at Object.t.setComputedState [as function] (file:///C:/Users/rafa/AppData/Local/Programs/cerebral-debugger/resources/app.asar/electron/build/bundle.js:20:174081)`

**Comment by coldserenity** [comment]
Forgot to mention. In my case, it's Cerebral Debugger v3.0.0
I have tried v2.5.1; at a glance, it works properly

**Comment by christianalfoni** [comment]
Hi there! 

Sorry for an extremely late answer. There has been issues related to Cerebral debugger and hot reloading. The latest debugger version `3.1.0` and now in the `next` branch there is a fix for hot reloading.

Run latest debugger and install Cerebral with `cerebral@next` and whatever view layer you use, for example `@cerebral/react@next` to try it out or wait for pending release :)
